image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - rm -rf .terraform
  - terraform --version
  - echo $SVCACCOUNT | base64 -d > serviceaccount.json
  - terraform init

stages:
  - validate
  - plan
  - apply
  - terminate

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile

apply:
  stage: apply
  script:
    - terraform apply "planfile"
  dependencies:
    - plan
  artifacts:
    paths:
      - terraform.tfstate
  when: manual

terminate:
  stage: terminate
  script:
    - terraform destroy --auto-approve
  dependencies:
    - apply
  when: manual
